# Generated by Django 2.2.1 on 2019-05-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kviz', '0003_auto_20190526_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer_text1',
            new_name='answer_text',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_text2',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='answer_text3',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='solution_text',
        ),
        migrations.AddField(
            model_name='answers',
            name='solution',
            field=models.BooleanField(default=False),
        ),
    ]
